## Extractive Summarizer: SBERT Fine-Tuning + K-Means

Notebook này thực hiện:
1. **Fine-Tuning SBERT (Tiếng Anh & Tiếng Việt)** sử dụng tập cặp câu Oracle và `CosineSimilarityLoss`
3. **Đánh giá & Ablation Study**: So sánh Lead-3, TextRank, SBERT-No-KMeans và FineTuned-SBERT-KMeans trên các chỉ số ROUGE-1, ROUGE-2, ROUGE-L và Diversity Score.

In [ ]:
import torch
is_gpu = torch.cuda.is_available()
print(f"CUDA/GPU Available: {is_gpu}")
if is_gpu:
    gpu_name = torch.cuda.get_device_name(0)
    vram_gb = torch.cuda.get_device_properties(0).total_memory / (1024**3)
    print(f"Tên GPU: {gpu_name}")
    print(f"Tổng dung lượng VRAM: {vram_gb:.2f} GB")

CUDA/GPU Available: True
Tên GPU: Tesla T4
Tổng dung lượng VRAM: 14.56 GB

## 1. Cài đặt Môi trường & Thư viện

In [ ]:
import os
import sys

if 'colab' in str(get_ipython()):
    if not os.path.exists('Extractive-Summarizer'):
        !git clone https://github.com/kttt294/Extractive-Summarizer.git
    if os.path.exists('Extractive-Summarizer') and not os.getcwd().endswith('Extractive-Summarizer'):
        %cd Extractive-Summarizer
    !git pull
    !pip install -q -r requirements.txt
sys.path.append(os.getcwd())

Cloning into 'Extractive-Summarizer'...
remote: Enumerating objects: 390, done.
remote: Counting objects: 100% (188/188), done.
remote: Compressing objects: 100% (128/128), done.
remote: Total 390 (delta 109), reused 128 (delta 59), pack-reused 202 (from 1)
Receiving objects: 100% (390/390), 24.36 MiB | 45.04 MiB/s, done.
Resolving deltas: 100% (212/212), done.
/content/Extractive-Summarizer
Already up to date.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 21.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 124.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.3/7.3 MB 101.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.5/73.5 kB 7.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.1/211.1 kB 22.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.5/81.5 kB 8.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 113.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 118.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.9/105.9 kB 10.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 76.7 MB/s eta 0:00:00
  Building wheel for langdetect (setup.py) ... done
  Building wheel for rouge-score (setup.py) ... done
  Building wheel for tinysegmenter (setup.py) ... done
  Building wheel for breadability (setup.py) ... done
  Building wheel for feedfinder2 (setup.py) ... done
  Building wheel for jieba3k (setup.py) ... done
  Building wheel for docopt (setup.py) ... done
  Building wheel for sgmllib3k (setup.py) ... done

## 2. Fine-Tuning Mô hình SBERT Song ngữ (English & Vietnamese)

**Cấu hình Siêu tham số:**
- `sample_data_count = 3000`: Lấy 3,000 bài báo (~12,000 cặp câu Oracle).
- `epochs = 3`: Chuẩn mực tối ưu từ tác giả Sentence-Transformers để Fine-tune Bi-Encoder qua CosineSimilarityLoss.
- `batch_size = 32`: Tối ưu hiệu năng tính toán ma trận trên GPU NVIDIA T4.

In [ ]:
from src.train import train_finetune_sbert

print("BẮT ĐẦU FINE-TUNE SBERT TIẾNG ANH (3,000 BÀI BÁO)")
model_en_path = train_finetune_sbert(lang='en', epochs=3, batch_size=32, sample_data_count=3000)

print("\n\nBẮT ĐẦU FINE-TUNE SBERT TIẾNG VIỆT (3,000 BÀI BÁO)")
model_vi_path = train_finetune_sbert(lang='vi', epochs=3, batch_size=32, sample_data_count=3000)

BẮT ĐẦU FINE-TUNE SBERT TIẾNG ANH (3,000 BÀI BÁO)
Nạp mô hình SBERT Gốc: sentence-transformers/all-MiniLM-L6-v2

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Đang nạp bộ dữ liệu EN [Split: train] bằng Chiến thuật Lấy mẫu Phân tầng (số lượng=3000)...

README.md:   0%|          | 0.00/15.6k [00:00<?, ?B/s]

README.md:   0%|          | 0.00/15.6k [00:00<?, ?B/s]

3.0.0/train-00000-of-00003.parquet: reconstructing file:   0%|          |  0.00B /  257MB

3.0.0/train-00000-of-00003.parquet: downloading bytes:           |  0.00B

3.0.0/train-00001-of-00003.parquet: reconstructing file:   0%|          |  0.00B /  257MB

3.0.0/train-00001-of-00003.parquet: downloading bytes:           |  0.00B

3.0.0/train-00002-of-00003.parquet: reconstructing file:   0%|          |  0.00B /  259MB

3.0.0/train-00002-of-00003.parquet: downloading bytes:           |  0.00B

3.0.0/validation-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 34.7MB

3.0.0/validation-00000-of-00001.parquet: downloading bytes:           |  0.00B

3.0.0/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 30.0MB

3.0.0/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/287113 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/13368 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/11490 [00:00<?, ? examples/s]

Đã nạp thành công 3000 bài báo Tinh hoa EN [train] qua lọc phân tầng.
Đang tạo các cặp câu Oracle cho Fine-Tuning (mục tiêu: 12000 cặp).
Đã khởi tạo thành công 12001 cặp câu huấn luyện Oracle.

Computing widget examples:   0%|          | 0/1 [00:00<?, ?example/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Fine-Tuning hoàn tất. Mô hình đã được lưu tại: /content/Extractive-Summarizer/models/finetuned_sbert_en



BẮT ĐẦU FINE-TUNE SBERT TIẾNG VIỆT (3,000 BÀI BÁO)
Nạp mô hình SBERT Gốc: bkai-foundation-models/vietnamese-bi-encoder

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/123 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/6.46k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/777 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  540MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/895k [00:00<?, ?B/s]

bpe.codes:   0%|          | 0.00/1.14M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/22.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/167 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/270 [00:00<?, ?B/s]

Đang nạp bộ dữ liệu VI [Split: train] bằng Chiến thuật Lấy mẫu Phân tầng (số lượng=3000)...

README.md:   0%|          | 0.00/748 [00:00<?, ?B/s]

data/train-00000-of-00001-84acb79f6c6547(…): reconstructing file:   0%|          |  0.00B /  170MB

data/train-00000-of-00001-84acb79f6c6547(…): downloading bytes:           |  0.00B

data/validation-00000-of-00001-210cc51bf(…): reconstructing file:   0%|          |  0.00B / 38.3MB

data/validation-00000-of-00001-210cc51bf(…): downloading bytes:           |  0.00B

data/test-00000-of-00001-123f98d55067eb7(…): reconstructing file:   0%|          |  0.00B / 38.8MB

data/test-00000-of-00001-123f98d55067eb7(…): downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/99134 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/22184 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/22498 [00:00<?, ? examples/s]

Đã nạp thành công 3000 bài báo Tinh hoa VI [train] qua lọc phân tầng.
Đang tạo các cặp câu Oracle cho Fine-Tuning (mục tiêu: 12000 cặp).
Đã khởi tạo thành công 12001 cặp câu huấn luyện Oracle.

Computing widget examples:   0%|          | 0/1 [00:00<?, ?example/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Fine-Tuning hoàn tất. Mô hình đã được lưu tại: /content/Extractive-Summarizer/models/finetuned_sbert_vi

In [ ]:
# finetune lại, dùng sentence-transformers/all-mpnet-base-v2

from src.train import train_finetune_sbert

print("BẮT ĐẦU FINE-TUNE SBERT TIẾNG ANH (3,000 BÀI BÁO)")
model_en_path = train_finetune_sbert(lang='en', epochs=3, batch_size=32, sample_data_count=3000)

BẮT ĐẦU FINE-TUNE SBERT TIẾNG ANH (3,000 BÀI BÁO)
Nạp mô hình SBERT Gốc: sentence-transformers/all-mpnet-base-v2

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/11.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  438MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/15.6k [00:00<?, ?B/s]

README.md:   0%|          | 0.00/15.6k [00:00<?, ?B/s]

3.0.0/train-00000-of-00003.parquet: reconstructing file:   0%|          |  0.00B /  257MB

3.0.0/train-00000-of-00003.parquet: downloading bytes:           |  0.00B

3.0.0/train-00001-of-00003.parquet: reconstructing file:   0%|          |  0.00B /  257MB

3.0.0/train-00001-of-00003.parquet: downloading bytes:           |  0.00B

3.0.0/train-00002-of-00003.parquet: reconstructing file:   0%|          |  0.00B /  259MB

3.0.0/train-00002-of-00003.parquet: downloading bytes:           |  0.00B

3.0.0/validation-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 34.7MB

3.0.0/validation-00000-of-00001.parquet: downloading bytes:           |  0.00B

3.0.0/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 30.0MB

3.0.0/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/287113 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/13368 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/11490 [00:00<?, ? examples/s]

Đang tạo các cặp câu Oracle cho Fine-Tuning (mục tiêu: 12000 cặp).
Đã khởi tạo thành công 12001 cặp câu huấn luyện Oracle.

Computing widget examples:   0%|          | 0/1 [00:00<?, ?example/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Fine-Tuning hoàn tất. Mô hình đã được lưu tại: /content/Extractive-Summarizer/models/finetuned_sbert_en

In [ ]:
from src.train import train_finetune_sbert

print("BẮT ĐẦU FINE-TUNE SBERT TIẾNG VIỆT (3,000 BÀI BÁO)")
model_vi_path = train_finetune_sbert(lang='vi', epochs=3, batch_size=32, sample_data_count=3000)

BẮT ĐẦU FINE-TUNE SBERT TIẾNG VIỆT (3,000 BÀI BÁO)
Nạp mô hình SBERT Gốc: bkai-foundation-models/vietnamese-bi-encoder

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/123 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/6.46k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/777 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  540MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/895k [00:00<?, ?B/s]

bpe.codes:   0%|          | 0.00/1.14M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/22.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/167 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/270 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/748 [00:00<?, ?B/s]

data/train-00000-of-00001-84acb79f6c6547(…): reconstructing file:   0%|          |  0.00B /  170MB

data/train-00000-of-00001-84acb79f6c6547(…): downloading bytes:           |  0.00B

data/validation-00000-of-00001-210cc51bf(…): reconstructing file:   0%|          |  0.00B / 38.3MB

data/validation-00000-of-00001-210cc51bf(…): downloading bytes:           |  0.00B

data/test-00000-of-00001-123f98d55067eb7(…): reconstructing file:   0%|          |  0.00B / 38.8MB

data/test-00000-of-00001-123f98d55067eb7(…): downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/99134 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/22184 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/22498 [00:00<?, ? examples/s]

Đang tạo các cặp câu Oracle cho Fine-Tuning (mục tiêu: 12000 cặp).
Đã khởi tạo thành công 12001 cặp câu huấn luyện Oracle.

Computing widget examples:   0%|          | 0/1 [00:00<?, ?example/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Fine-Tuning hoàn tất. Mô hình đã được lưu tại: /content/Extractive-Summarizer/models/finetuned_sbert_vi

In [ ]:
import shutil
shutil.make_archive('finetuned_sbert_en', 'zip', './models/finetuned_sbert_en')
shutil.make_archive('finetuned_sbert_vi', 'zip', './models/finetuned_sbert_vi')
if 'colab' in str(get_ipython()):
    from google.colab import files
    files.download('finetuned_sbert_en.zip')
    files.download('finetuned_sbert_vi.zip')
    print("Đã nén và tải weights về máy.")

Đã nén và tải weights về máy.

## 3. Khung Đánh giá Thực nghiệm & Ablation Study
So sánh kết quả giữa 5 phương pháp:
1. **Lead-3 Baseline**
2. **TextRank Baseline**
3. **Pretrained-SBERT-KMeans** *(Ablation Study)*
4. **SBERT-No-KMeans** *(Ablation Study)*
5. **FineTuned-SBERT-KMeans** *(Mô hình Đề xuất)*

In [ ]:
from src.evaluate import evaluate_framework

evaluate_framework(lang='en', sample_count=500)
evaluate_framework(lang='vi', sample_count=500)

Đánh giá trên ngôn ngữ EN - Số lượng: 500

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

======================================================================================================================================================
Mô hình                    | Silhouette | Diversity  | Compress (%) | ROUGE-1 (%)        | ROUGE-2 (%)        | ROUGE-L (%)        | SBERT Cosine   | BERTScore
======================================================================================================================================================
Lead-3                     | N/A        | 0.6047     | 81.06        | 31.65 ± 11.76      | 13.16 ± 10.42      | 21.57 ± 9.52       | 0.7118 ± 0.1585 | 0.8641 ± 0.0225
TextRank                   | N/A        | 0.6045     | 73.73        | 23.81 ± 10.19      | 7.95 ± 8.35        | 16.09 ± 8.13       | 0.6510 ± 0.1359 | 0.8525 ± 0.0206
Pretrained-SBERT-KMeans    | 0.0786     | 0.7370     | 83.16        | 27.31 ± 10.94      | 9.44 ± 8.91        | 18.44 ± 8.98       | 0.6763 ± 0.1292 | 0.8571 ± 0.0203
SBERT-No-KMeans            | N/A        | 0.5258     | 80.78        | 25.75 ± 11.67      | 8.95 ± 9.30        | 17.56 ± 9.36       | 0.6715 ± 0.1325 | 0.8562 ± 0.0223
FineTuned-SBERT-KMeans     | 0.0507     | 0.7064     | 83.01        | 26.54 ± 11.14      | 8.80 ± 8.45        | 17.76 ± 8.69       | 0.6685 ± 0.1360 | 0.8563 ± 0.0201
======================================================================================================================================================

[Statistical Significance Test - Paired t-test (Lead-3 vs FineTuned-SBERT-KMeans)]
- ROUGE-1 p-value:      5.8649e-22 (Significant (p<0.05))
- Real BERTScore p-value: 4.4282e-16 (Significant (p<0.05))



Đánh giá trên ngôn ngữ VI - Số lượng: 500

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

======================================================================================================================================================
Mô hình                    | Silhouette | Diversity  | Compress (%) | ROUGE-1 (%)        | ROUGE-2 (%)        | ROUGE-L (%)        | SBERT Cosine   | BERTScore
======================================================================================================================================================
Lead-3                     | N/A        | 0.6472     | 73.93        | 47.75 ± 9.80       | 21.52 ± 9.03       | 28.94 ± 6.29       | 0.5374 ± 0.1687 | 0.7143 ± 0.0383
TextRank                   | N/A        | 0.5679     | 74.36        | 47.20 ± 10.25      | 21.68 ± 8.91       | 29.16 ± 6.55       | 0.5464 ± 0.1660 | 0.7171 ± 0.0374
Pretrained-SBERT-KMeans    | 0.0949     | 0.7444     | 81.01        | 51.21 ± 10.11      | 21.57 ± 9.49       | 30.44 ± 7.26       | 0.5242 ± 0.1616 | 0.7183 ± 0.0355
SBERT-No-KMeans            | N/A        | 0.6062     | 82.15        | 51.70 ± 9.60       | 21.69 ± 9.46       | 30.68 ± 7.12       | 0.5178 ± 0.1652 | 0.7217 ± 0.0371
FineTuned-SBERT-KMeans     | 0.1759     | 0.7582     | 84.93        | 52.91 ± 9.46       | 20.43 ± 10.39      | 30.60 ± 7.29       | 0.4813 ± 0.1741 | 0.7110 ± 0.0388
======================================================================================================================================================

[Statistical Significance Test - Paired t-test (Lead-3 vs FineTuned-SBERT-KMeans)]
- ROUGE-1 p-value:      2.8332e-29 (Significant (p<0.05))
- Real BERTScore p-value: 2.6014e-02 (Significant (p<0.05))

##4. Tinh chỉnh Siêu tham số

In [ ]:
from src.tune_hyperparams import grid_search

grid_search(lang='vi', sample_count=500)

Bắt đầu tinh chỉnh siêu tham số trên tập tin tức VI (VietNews/CNN) với 500 mẫu...
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.05, Theta = 0.65
  -> ROUGE-1: 52.51%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.05, Theta = 0.70
  -> ROUGE-1: 52.53%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.05, Theta = 0.75
  -> ROUGE-1: 52.51%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.05, Theta = 0.80
  -> ROUGE-1: 52.52%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.05, Theta = 0.85
  -> ROUGE-1: 52.59%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.10, Theta = 0.65
  -> ROUGE-1: 53.66%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.10, Theta = 0.70
  -> ROUGE-1: 53.68%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.10, Theta = 0.75
  -> ROUGE-1: 53.62%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.10, Theta = 0.80
  -> ROUGE-1: 53.62%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.10, Theta = 0.85
  -> ROUGE-1: 53.65%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.15, Theta = 0.65
  -> ROUGE-1: 52.92%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.15, Theta = 0.70
  -> ROUGE-1: 52.95%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.15, Theta = 0.75
  -> ROUGE-1: 52.92%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.15, Theta = 0.80
  -> ROUGE-1: 52.92%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.15, Theta = 0.85
  -> ROUGE-1: 52.93%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.20, Theta = 0.65
  -> ROUGE-1: 50.56%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.20, Theta = 0.70
  -> ROUGE-1: 50.59%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.20, Theta = 0.75
  -> ROUGE-1: 50.56%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.20, Theta = 0.80
  -> ROUGE-1: 50.54%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.20, Theta = 0.85
  -> ROUGE-1: 50.55%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.25, Theta = 0.65
  -> ROUGE-1: 47.84%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.25, Theta = 0.70
  -> ROUGE-1: 47.87%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.25, Theta = 0.75
  -> ROUGE-1: 47.84%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.25, Theta = 0.80
  -> ROUGE-1: 47.84%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.25, Theta = 0.85
  -> ROUGE-1: 47.86%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.05, Theta = 0.65
  -> ROUGE-1: 52.39%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.05, Theta = 0.70
  -> ROUGE-1: 52.42%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.05, Theta = 0.75
  -> ROUGE-1: 52.40%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.05, Theta = 0.80
  -> ROUGE-1: 52.40%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.05, Theta = 0.85
  -> ROUGE-1: 52.48%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.10, Theta = 0.65
  -> ROUGE-1: 53.58%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.10, Theta = 0.70
  -> ROUGE-1: 53.60%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.10, Theta = 0.75
  -> ROUGE-1: 53.54%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.10, Theta = 0.80
  -> ROUGE-1: 53.54%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.10, Theta = 0.85
  -> ROUGE-1: 53.57%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.15, Theta = 0.65
  -> ROUGE-1: 52.91%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.15, Theta = 0.70
  -> ROUGE-1: 52.94%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.15, Theta = 0.75
  -> ROUGE-1: 52.91%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.15, Theta = 0.80
  -> ROUGE-1: 52.91%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.15, Theta = 0.85
  -> ROUGE-1: 52.93%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.20, Theta = 0.65
  -> ROUGE-1: 50.58%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.20, Theta = 0.70
  -> ROUGE-1: 50.60%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.20, Theta = 0.75
  -> ROUGE-1: 50.57%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.20, Theta = 0.80
  -> ROUGE-1: 50.56%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.20, Theta = 0.85
  -> ROUGE-1: 50.57%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.25, Theta = 0.65
  -> ROUGE-1: 47.85%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.25, Theta = 0.70
  -> ROUGE-1: 47.87%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.25, Theta = 0.75
  -> ROUGE-1: 47.85%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.25, Theta = 0.80
  -> ROUGE-1: 47.85%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.25, Theta = 0.85
  -> ROUGE-1: 47.86%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.05, Theta = 0.65
  -> ROUGE-1: 52.39%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.05, Theta = 0.70
  -> ROUGE-1: 52.42%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.05, Theta = 0.75
  -> ROUGE-1: 52.40%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.05, Theta = 0.80
  -> ROUGE-1: 52.40%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.05, Theta = 0.85
  -> ROUGE-1: 52.48%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.10, Theta = 0.65
  -> ROUGE-1: 53.58%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.10, Theta = 0.70
  -> ROUGE-1: 53.60%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.10, Theta = 0.75
  -> ROUGE-1: 53.54%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.10, Theta = 0.80
  -> ROUGE-1: 53.54%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.10, Theta = 0.85
  -> ROUGE-1: 53.57%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.15, Theta = 0.65
  -> ROUGE-1: 52.91%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.15, Theta = 0.70
  -> ROUGE-1: 52.93%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.15, Theta = 0.75
  -> ROUGE-1: 52.91%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.15, Theta = 0.80
  -> ROUGE-1: 52.91%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.15, Theta = 0.85
  -> ROUGE-1: 52.92%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.20, Theta = 0.65
  -> ROUGE-1: 50.57%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.20, Theta = 0.70
  -> ROUGE-1: 50.60%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.20, Theta = 0.75
  -> ROUGE-1: 50.56%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.20, Theta = 0.80
  -> ROUGE-1: 50.55%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.20, Theta = 0.85
  -> ROUGE-1: 50.57%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.25, Theta = 0.65
  -> ROUGE-1: 47.85%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.25, Theta = 0.70
  -> ROUGE-1: 47.87%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.25, Theta = 0.75
  -> ROUGE-1: 47.85%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.25, Theta = 0.80
  -> ROUGE-1: 47.85%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.25, Theta = 0.85
  -> ROUGE-1: 47.86%

============================================================
BẢNG KẾT QUẢ GRID SEARCH (ROUGE-1 %)
============================================================

[ Lambda = 0.20 ]
Alpha \ Theta   | 0.65 | 0.70 | 0.75 | 0.80 | 0.85
------------------------------------------------------------
0.05            | 52.51 | 52.53 | 52.51 | 52.52 | 52.59
0.10            | 53.66 | 53.68 | 53.62 | 53.62 | 53.65
0.15            | 52.92 | 52.95 | 52.92 | 52.92 | 52.93
0.20            | 50.56 | 50.59 | 50.56 | 50.54 | 50.55
0.25            | 47.84 | 47.87 | 47.84 | 47.84 | 47.86

[ Lambda = 0.35 ]
Alpha \ Theta   | 0.65 | 0.70 | 0.75 | 0.80 | 0.85
------------------------------------------------------------
0.05            | 52.39 | 52.42 | 52.40 | 52.40 | 52.48
0.10            | 53.58 | 53.60 | 53.54 | 53.54 | 53.57
0.15            | 52.91 | 52.94 | 52.91 | 52.91 | 52.93
0.20            | 50.58 | 50.60 | 50.57 | 50.56 | 50.57
0.25            | 47.85 | 47.87 | 47.85 | 47.85 | 47.86

[ Lambda = 0.50 ]
Alpha \ Theta   | 0.65 | 0.70 | 0.75 | 0.80 | 0.85
------------------------------------------------------------
0.05            | 52.39 | 52.42 | 52.40 | 52.40 | 52.48
0.10            | 53.58 | 53.60 | 53.54 | 53.54 | 53.57
0.15            | 52.91 | 52.93 | 52.91 | 52.91 | 52.92
0.20            | 50.57 | 50.60 | 50.56 | 50.55 | 50.57
0.25            | 47.85 | 47.87 | 47.85 | 47.85 | 47.86

============================================================
CẤU HÌNH TỐI ƯU NHẤT: Lambda = 0.20, Alpha = 0.10, Theta = 0.70
ROUGE-1 CAO NHẤT: 53.68%

In [ ]:
from src.tune_hyperparams import grid_search

grid_search(lang='en', sample_count=500)

Bắt đầu tinh chỉnh siêu tham số trên tập tin tức EN (VietNews/CNN) với 500 mẫu...
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.05, Theta = 0.65
  -> ROUGE-1: 26.32%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.05, Theta = 0.70
  -> ROUGE-1: 26.32%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.05, Theta = 0.75
  -> ROUGE-1: 26.32%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.05, Theta = 0.80
  -> ROUGE-1: 26.32%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.05, Theta = 0.85
  -> ROUGE-1: 26.32%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.10, Theta = 0.65
  -> ROUGE-1: 26.26%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.10, Theta = 0.70
  -> ROUGE-1: 26.26%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.10, Theta = 0.75
  -> ROUGE-1: 26.26%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.10, Theta = 0.80
  -> ROUGE-1: 26.26%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.10, Theta = 0.85
  -> ROUGE-1: 26.26%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.15, Theta = 0.65
  -> ROUGE-1: 26.29%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.15, Theta = 0.70
  -> ROUGE-1: 26.29%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.15, Theta = 0.75
  -> ROUGE-1: 26.29%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.15, Theta = 0.80
  -> ROUGE-1: 26.29%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.15, Theta = 0.85
  -> ROUGE-1: 26.29%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.20, Theta = 0.65
  -> ROUGE-1: 25.68%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.20, Theta = 0.70
  -> ROUGE-1: 25.68%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.20, Theta = 0.75
  -> ROUGE-1: 25.68%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.20, Theta = 0.80
  -> ROUGE-1: 25.68%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.20, Theta = 0.85
  -> ROUGE-1: 25.68%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.25, Theta = 0.65
  -> ROUGE-1: 24.96%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.25, Theta = 0.70
  -> ROUGE-1: 24.96%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.25, Theta = 0.75
  -> ROUGE-1: 24.96%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.25, Theta = 0.80
  -> ROUGE-1: 24.96%
Đang chạy cấu hình: Lambda = 0.20, Alpha = 0.25, Theta = 0.85
  -> ROUGE-1: 24.96%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.05, Theta = 0.65
  -> ROUGE-1: 26.90%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.05, Theta = 0.70
  -> ROUGE-1: 26.90%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.05, Theta = 0.75
  -> ROUGE-1: 26.90%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.05, Theta = 0.80
  -> ROUGE-1: 26.90%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.05, Theta = 0.85
  -> ROUGE-1: 26.90%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.10, Theta = 0.65
  -> ROUGE-1: 26.68%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.10, Theta = 0.70
  -> ROUGE-1: 26.68%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.10, Theta = 0.75
  -> ROUGE-1: 26.68%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.10, Theta = 0.80
  -> ROUGE-1: 26.68%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.10, Theta = 0.85
  -> ROUGE-1: 26.68%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.15, Theta = 0.65
  -> ROUGE-1: 26.54%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.15, Theta = 0.70
  -> ROUGE-1: 26.54%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.15, Theta = 0.75
  -> ROUGE-1: 26.54%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.15, Theta = 0.80
  -> ROUGE-1: 26.54%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.15, Theta = 0.85
  -> ROUGE-1: 26.54%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.20, Theta = 0.65
  -> ROUGE-1: 25.82%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.20, Theta = 0.70
  -> ROUGE-1: 25.82%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.20, Theta = 0.75
  -> ROUGE-1: 25.82%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.20, Theta = 0.80
  -> ROUGE-1: 25.82%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.20, Theta = 0.85
  -> ROUGE-1: 25.82%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.25, Theta = 0.65
  -> ROUGE-1: 25.15%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.25, Theta = 0.70
  -> ROUGE-1: 25.15%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.25, Theta = 0.75
  -> ROUGE-1: 25.15%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.25, Theta = 0.80
  -> ROUGE-1: 25.15%
Đang chạy cấu hình: Lambda = 0.35, Alpha = 0.25, Theta = 0.85
  -> ROUGE-1: 25.15%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.05, Theta = 0.65
  -> ROUGE-1: 27.04%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.05, Theta = 0.70
  -> ROUGE-1: 27.04%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.05, Theta = 0.75
  -> ROUGE-1: 27.04%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.05, Theta = 0.80
  -> ROUGE-1: 27.04%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.05, Theta = 0.85
  -> ROUGE-1: 27.04%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.10, Theta = 0.65
  -> ROUGE-1: 27.01%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.10, Theta = 0.70
  -> ROUGE-1: 27.01%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.10, Theta = 0.75
  -> ROUGE-1: 27.01%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.10, Theta = 0.80
  -> ROUGE-1: 27.01%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.10, Theta = 0.85
  -> ROUGE-1: 27.01%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.15, Theta = 0.65
  -> ROUGE-1: 26.74%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.15, Theta = 0.70
  -> ROUGE-1: 26.74%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.15, Theta = 0.75
  -> ROUGE-1: 26.74%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.15, Theta = 0.80
  -> ROUGE-1: 26.74%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.15, Theta = 0.85
  -> ROUGE-1: 26.74%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.20, Theta = 0.65
  -> ROUGE-1: 26.07%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.20, Theta = 0.70
  -> ROUGE-1: 26.07%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.20, Theta = 0.75
  -> ROUGE-1: 26.07%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.20, Theta = 0.80
  -> ROUGE-1: 26.07%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.20, Theta = 0.85
  -> ROUGE-1: 26.07%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.25, Theta = 0.65
  -> ROUGE-1: 25.16%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.25, Theta = 0.70
  -> ROUGE-1: 25.16%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.25, Theta = 0.75
  -> ROUGE-1: 25.16%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.25, Theta = 0.80
  -> ROUGE-1: 25.16%
Đang chạy cấu hình: Lambda = 0.50, Alpha = 0.25, Theta = 0.85
  -> ROUGE-1: 25.16%

============================================================
BẢNG KẾT QUẢ GRID SEARCH (ROUGE-1 %)
============================================================

[ Lambda = 0.20 ]
Alpha \ Theta   | 0.65 | 0.70 | 0.75 | 0.80 | 0.85
------------------------------------------------------------
0.05            | 26.32 | 26.32 | 26.32 | 26.32 | 26.32
0.10            | 26.26 | 26.26 | 26.26 | 26.26 | 26.26
0.15            | 26.29 | 26.29 | 26.29 | 26.29 | 26.29
0.20            | 25.68 | 25.68 | 25.68 | 25.68 | 25.68
0.25            | 24.96 | 24.96 | 24.96 | 24.96 | 24.96

[ Lambda = 0.35 ]
Alpha \ Theta   | 0.65 | 0.70 | 0.75 | 0.80 | 0.85
------------------------------------------------------------
0.05            | 26.90 | 26.90 | 26.90 | 26.90 | 26.90
0.10            | 26.68 | 26.68 | 26.68 | 26.68 | 26.68
0.15            | 26.54 | 26.54 | 26.54 | 26.54 | 26.54
0.20            | 25.82 | 25.82 | 25.82 | 25.82 | 25.82
0.25            | 25.15 | 25.15 | 25.15 | 25.15 | 25.15

[ Lambda = 0.50 ]
Alpha \ Theta   | 0.65 | 0.70 | 0.75 | 0.80 | 0.85
------------------------------------------------------------
0.05            | 27.04 | 27.04 | 27.04 | 27.04 | 27.04
0.10            | 27.01 | 27.01 | 27.01 | 27.01 | 27.01
0.15            | 26.74 | 26.74 | 26.74 | 26.74 | 26.74
0.20            | 26.07 | 26.07 | 26.07 | 26.07 | 26.07
0.25            | 25.16 | 25.16 | 25.16 | 25.16 | 25.16

============================================================
CẤU HÌNH TỐI ƯU NHẤT: Lambda = 0.50, Alpha = 0.05, Theta = 0.65
ROUGE-1 CAO NHẤT: 27.04%

## 5. Khung Đánh giá Thực nghiệm & Ablation Study (sau khi tinh chỉnh siêu tham số)
So sánh kết quả giữa 5 phương pháp:
1. **Lead-3 Baseline**
2. **TextRank Baseline**
3. **Pretrained-SBERT-KMeans** *(Ablation Study)*
4. **SBERT-No-KMeans** *(Ablation Study)*
5. **FineTuned-SBERT-KMeans** *(Mô hình Đề xuất)*

In [ ]:
from src.evaluate import evaluate_framework

evaluate_framework(lang='en', sample_count=2000)
evaluate_framework(lang='vi', sample_count=2000)

Đánh giá trên ngôn ngữ EN - Số lượng: 2000

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/15.6k [00:00<?, ?B/s]

README.md:   0%|          | 0.00/15.6k [00:00<?, ?B/s]

3.0.0/train-00000-of-00003.parquet: reconstructing file:   0%|          |  0.00B /  257MB

3.0.0/train-00000-of-00003.parquet: downloading bytes:           |  0.00B

3.0.0/train-00001-of-00003.parquet: reconstructing file:   0%|          |  0.00B /  257MB

3.0.0/train-00001-of-00003.parquet: downloading bytes:           |  0.00B

3.0.0/train-00002-of-00003.parquet: reconstructing file:   0%|          |  0.00B /  259MB

3.0.0/train-00002-of-00003.parquet: downloading bytes:           |  0.00B

3.0.0/validation-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 34.7MB

3.0.0/validation-00000-of-00001.parquet: downloading bytes:           |  0.00B

3.0.0/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 30.0MB

3.0.0/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/287113 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/13368 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/11490 [00:00<?, ? examples/s]

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/11.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  438MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/482 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.42GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

modules.json:   0%|          | 0.00/429 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/284 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/13.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/241 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/576 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  438MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/584 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/712k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/90.0 [00:00<?, ?B/s]

======================================================================================================================================================
Mô hình                    | Silhouette | Diversity  | Compress (%) | ROUGE-1 (%)        | ROUGE-2 (%)        | ROUGE-L (%)        | SBERT Cosine   | BERTScore
======================================================================================================================================================
Lead-3                     | N/A        | 0.5958     | 81.26        | 35.18 ± 12.53      | 14.98 ± 11.26      | 23.09 ± 10.36      | 0.7331 ± 0.1450 | 0.8674 ± 0.0235
TextRank                   | N/A        | 0.5848     | 75.28        | 26.53 ± 11.20      | 9.25 ± 9.31        | 17.34 ± 8.84       | 0.6708 ± 0.1372 | 0.8529 ± 0.0220
Pretrained-SBERT-KMeans    | 0.0923     | 0.7198     | 88.42        | 29.83 ± 12.02      | 10.31 ± 10.17      | 20.07 ± 9.82       | 0.6532 ± 0.1465 | 0.8596 ± 0.0217
SBERT-No-KMeans            | N/A        | 0.4564     | 87.26        | 29.65 ± 12.80      | 10.32 ± 10.40      | 19.80 ± 10.16      | 0.6512 ± 0.1634 | 0.8605 ± 0.0244
FineTuned-SBERT-KMeans     | 0.0683     | 0.6812     | 88.10        | 29.92 ± 12.64      | 10.36 ± 10.42      | 19.94 ± 10.10      | 0.6495 ± 0.1559 | 0.8602 ± 0.0225
======================================================================================================================================================

[Statistical Significance Test - Paired t-test (Lead-3 vs FineTuned-SBERT-KMeans)]
- ROUGE-1 p-value:      8.7169e-78 (Significant (p<0.05))
- Real BERTScore p-value: 4.8270e-44 (Significant (p<0.05))



Đánh giá trên ngôn ngữ VI - Số lượng: 2000

README.md:   0%|          | 0.00/748 [00:00<?, ?B/s]

data/train-00000-of-00001-84acb79f6c6547(…): reconstructing file:   0%|          |  0.00B /  170MB

data/train-00000-of-00001-84acb79f6c6547(…): downloading bytes:           |  0.00B

data/validation-00000-of-00001-210cc51bf(…): reconstructing file:   0%|          |  0.00B / 38.3MB

data/validation-00000-of-00001-210cc51bf(…): downloading bytes:           |  0.00B

data/test-00000-of-00001-123f98d55067eb7(…): reconstructing file:   0%|          |  0.00B / 38.8MB

data/test-00000-of-00001-123f98d55067eb7(…): downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/99134 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/22184 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/22498 [00:00<?, ? examples/s]

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/123 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/6.46k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/777 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  540MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/895k [00:00<?, ?B/s]

bpe.codes:   0%|          | 0.00/1.14M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/22.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/167 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/270 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  714MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

modules.json:   0%|          | 0.00/277 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/284 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/15.4k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/241 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/753 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  540MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/1.22k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/895k [00:00<?, ?B/s]

bpe.codes:   0%|          | 0.00/1.14M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/22.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/90.0 [00:00<?, ?B/s]

======================================================================================================================================================
Mô hình                    | Silhouette | Diversity  | Compress (%) | ROUGE-1 (%)        | ROUGE-2 (%)        | ROUGE-L (%)        | SBERT Cosine   | BERTScore
======================================================================================================================================================
Lead-3                     | N/A        | 0.6486     | 77.37        | 48.77 ± 10.01      | 22.92 ± 9.78       | 29.96 ± 7.29       | 0.5657 ± 0.1740 | 0.7229 ± 0.0398
TextRank                   | N/A        | 0.5533     | 76.50        | 46.51 ± 10.24      | 21.96 ± 8.91       | 29.14 ± 6.73       | 0.5552 ± 0.1742 | 0.7178 ± 0.0391
Pretrained-SBERT-KMeans    | 0.0921     | 0.7435     | 84.80        | 53.52 ± 9.43       | 22.39 ± 9.87       | 31.34 ± 7.40       | 0.5299 ± 0.1730 | 0.7222 ± 0.0377
SBERT-No-KMeans            | N/A        | 0.5936     | 85.11        | 53.97 ± 9.42       | 22.28 ± 9.92       | 31.46 ± 7.31       | 0.5213 ± 0.1718 | 0.7241 ± 0.0382
FineTuned-SBERT-KMeans     | 0.2050     | 0.7641     | 87.79        | 54.72 ± 9.31       | 21.57 ± 10.87      | 31.66 ± 7.80       | 0.4948 ± 0.1871 | 0.7185 ± 0.0408
======================================================================================================================================================

[Statistical Significance Test - Paired t-test (Lead-3 vs FineTuned-SBERT-KMeans)]
- ROUGE-1 p-value:      1.0773e-126 (Significant (p<0.05))
- Real BERTScore p-value: 2.5078e-08 (Significant (p<0.05))

##6. Đánh giá mở rộng trên tập PubMed & Reddit TIFU
Đánh giá khả năng của thuật toán K-Means trên các văn bản siêu dài (PubMed) và văn phong mạng xã hội (Reddit).

In [ ]:
from src.evaluate_extra import run_extra_evaluations

run_extra_evaluations(num_samples=500)

`trust_remote_code` is not supported anymore.
Please check that the Hugging Face dataset 'ccdv/pubmed-summarization' isn't based on a loading script and remove `trust_remote_code`.
If the dataset is based on a loading script, please ask the dataset author to remove it and convert it to a standard format like Parquet.
ERROR:datasets.load:`trust_remote_code` is not supported anymore.
Please check that the Hugging Face dataset 'ccdv/pubmed-summarization' isn't based on a loading script and remove `trust_remote_code`.
If the dataset is based on a loading script, please ask the dataset author to remove it and convert it to a standard format like Parquet.

Đánh giá trên ngôn ngữ EN - Số lượng: 500


Đánh giá trên tập dữ liệu ccdv/pubmed-summarization (document) - Số lượng: 500

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/3.80k [00:00<?, ?B/s]

document/train-00000-of-00005.parquet: reconstructing file:   0%|          |  0.00B /  208MB

document/train-00000-of-00005.parquet: downloading bytes:           |  0.00B

document/train-00001-of-00005.parquet: reconstructing file:   0%|          |  0.00B /  207MB

document/train-00001-of-00005.parquet: downloading bytes:           |  0.00B

document/train-00002-of-00005.parquet: reconstructing file:   0%|          |  0.00B /  205MB

document/train-00002-of-00005.parquet: downloading bytes:           |  0.00B

document/train-00003-of-00005.parquet: reconstructing file:   0%|          |  0.00B /  210MB

document/train-00003-of-00005.parquet: downloading bytes:           |  0.00B

document/train-00004-of-00005.parquet: reconstructing file:   0%|          |  0.00B /  208MB

document/train-00004-of-00005.parquet: downloading bytes:           |  0.00B

document/validation-00000-of-00001.parqu(…): reconstructing file:   0%|          |  0.00B / 58.6MB

document/validation-00000-of-00001.parqu(…): downloading bytes:           |  0.00B

document/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 58.5MB

document/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/119924 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/6633 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/6658 [00:00<?, ? examples/s]

Đang xử lý ccdv/pubmed-summarization:   0%|          | 0/500 [00:00<?, ?it/s]

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/11.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  438MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

modules.json:   0%|          | 0.00/429 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/284 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/13.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/241 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/576 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  438MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/584 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/712k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/90.0 [00:00<?, ?B/s]

Đang xử lý ccdv/pubmed-summarization: 100%|██████████| 500/500 [22:29<00:00,  2.70s/it]
`trust_remote_code` is not supported anymore.
Please check that the Hugging Face dataset 'dany0407/reddit_tifu_long' isn't based on a loading script and remove `trust_remote_code`.
If the dataset is based on a loading script, please ask the dataset author to remove it and convert it to a standard format like Parquet.
ERROR:datasets.load:`trust_remote_code` is not supported anymore.
Please check that the Hugging Face dataset 'dany0407/reddit_tifu_long' isn't based on a loading script and remove `trust_remote_code`.
If the dataset is based on a loading script, please ask the dataset author to remove it and convert it to a standard format like Parquet.

======================================================================================================================================================
Mô hình                    | Silhouette | Diversity  | Compress (%) | ROUGE-1 (%)        | ROUGE-2 (%)        | ROUGE-L (%)        | SBERT Cosine
======================================================================================================================================================
Lead-3                     | N/A        | 0.5054     | 95.27        | 27.34 ± 11.54      | 9.20 ± 11.89       | 17.25 ± 10.80      | 0.6959 ± 0.1463
TextRank                   | N/A        | 0.4333     | 90.38        | 36.03 ± 9.37       | 11.07 ± 7.93       | 19.39 ± 6.52       | 0.7475 ± 0.1272
Pretrained-SBERT-KMeans    | 0.1114     | 0.6915     | 94.63        | 33.34 ± 9.26       | 10.83 ± 8.60       | 19.01 ± 7.58       | 0.7749 ± 0.1124
SBERT-No-KMeans            | N/A        | 0.3279     | 92.88        | 39.13 ± 10.91      | 14.41 ± 9.24       | 21.77 ± 7.65       | 0.7828 ± 0.1321
FineTuned-SBERT-KMeans     | 0.0684     | 0.6288     | 94.23        | 35.58 ± 9.61       | 11.91 ± 8.48       | 19.92 ± 7.20       | 0.7806 ± 0.1165
FineTuned-Neutral-Lambda   | 0.0699     | 0.6279     | 93.79        | 35.75 ± 9.36       | 11.65 ± 7.49       | 19.26 ± 6.19       | 0.7684 ± 0.1183
======================================================================================================================================================



Đánh giá trên tập dữ liệu dany0407/reddit_tifu_long () - Số lượng: 500

README.md:   0%|          | 0.00/502 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 57.6MB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/42139 [00:00<?, ? examples/s]

Đang xử lý dany0407/reddit_tifu_long: 100%|██████████| 500/500 [04:37<00:00,  1.80it/s]

======================================================================================================================================================
Mô hình                    | Silhouette | Diversity  | Compress (%) | ROUGE-1 (%)        | ROUGE-2 (%)        | ROUGE-L (%)        | SBERT Cosine
======================================================================================================================================================
Lead-3                     | N/A        | 0.7223     | 74.43        | 15.16 ± 8.57       | 2.38 ± 3.41        | 10.56 ± 5.67       | 0.3920 ± 0.1707
TextRank                   | N/A        | 0.6631     | 61.73        | 15.25 ± 8.45       | 3.32 ± 4.03        | 10.84 ± 5.61       | 0.4796 ± 0.1632
Pretrained-SBERT-KMeans    | 0.0742     | 0.7907     | 82.54        | 17.19 ± 9.82       | 2.71 ± 4.60        | 12.35 ± 7.25       | 0.4119 ± 0.1578
SBERT-No-KMeans            | N/A        | 0.5690     | 78.92        | 17.58 ± 9.81       | 3.08 ± 4.77        | 12.47 ± 7.04       | 0.4335 ± 0.1648
FineTuned-SBERT-KMeans     | 0.0470     | 0.7893     | 82.56        | 17.04 ± 9.89       | 2.69 ± 4.56        | 12.01 ± 7.13       | 0.4012 ± 0.1632
FineTuned-Neutral-Lambda   | 0.0481     | 0.7973     | 83.24        | 16.91 ± 10.01      | 2.63 ± 4.35        | 11.97 ± 6.84       | 0.4072 ± 0.1636
======================================================================================================================================================

## 7. Demo Tóm tắt Văn bản Trực tiếp
Thử nghiệm trực tiếp pipeline tóm tắt trên một văn bản báo chí thực tế.

In [ ]:
from src.preprocess import resolve_language
from src.evaluate import run_sbert_pipeline

sample_1 = """
Năm nay, thí sinh được đăng kí tối đa 15 nguyện vọng và sắp xếp theo thứ tự ưu tiên từ cao xuống thấp; đối với các thí sinh đăng kí xét tuyển vào các ngành đào tạo giáo viên, các cơ sở đào tạo chỉ xét tuyển các nguyện vọng từ 1 đến 5.

Theo quy định, toàn bộ nguyện vọng xét tuyển của thí sinh đều phải đăng ký trên Hệ thống để xử lý chung, kể cả trường hợp thí sinh đã tham gia xét tuyển theo các phương thức riêng của cơ sở đào tạo (nếu có). Việc xử lý nguyện vọng tập trung nhằm bảo đảm nguyên tắc mỗi thí sinh chỉ trúng tuyển một nguyện vọng cao nhất, góp phần nâng cao tính công bằng, minh bạch trong tuyển sinh.

Lưu ý, các thí sinh đăng ký xét tuyển vào các chương trình đào tạo giáo viên, chương trình đào tạo thuộc lĩnh vực sức khỏe có cấp Giấy phép hành nghề, chương trình đào tạo thuộc lĩnh vực pháp luật căn cứ vào ngưỡng bảo đảm chất lượng đầu vào do các cơ sở đào tạo công bố để điều chỉnh nguyện vọng (các cơ sở đào tạo cập nhật ngưỡng đầu vào trước 17 giờ ngày 10/7/2026).

Từ ngày 15/7 đến 17 giờ ngày 21/7/2026, thí sinh nộp lệ phí xét tuyển trực tuyến theo số lượng nguyện vọng đã đăng kí.

Thí sinh cần tìm hiểu kỹ tài liệu hướng dẫn và phải thực hiện đúng, đủ, hết quy trình đăng ký xét tuyển. Thí sinh chưa rõ các nội dung khai báo, nộp lệ phí xét tuyển, có thể liên hệ với cán bộ tại các điểm tiếp nhận hoặc cán bộ của cơ sở đào tạo trực các số điện thoại hỗ trợ công tác tuyển sinh để được hướng dẫn.

Kết quả điểm trúng tuyển và danh sách thí sinh trúng tuyển đợt 1 sẽ được các cơ sở đào tạo công bố trước 17 giờ ngày 13/8/2026.

Sau khi có kết quả trúng tuyển, tất cả thí sinh, kể cả thí sinh trúng tuyển thẳng, phải xác nhận nhập học trực tuyến trước 17 giờ ngày 21/8/2026 nếu có nguyện vọng theo học. Đây là bước bắt buộc để hoàn tất quá trình trúng tuyển.
"""

lang = resolve_language(sample_1, user_choice='auto')
summary_text, summary_sents, sil_score, div_score = run_sbert_pipeline(sample_1, lang=lang, use_finetuned=True)

print(f"Ngôn ngữ tự động nhận diện: {lang.upper()}")
print(f"Chỉ số Nội tại (Intrinsic): Silhouette Score = {sil_score:.4f} | Diversity Score = {div_score:.4f}")
print(f"\n--- KẾT QUẢ TÓM TẮT TRÍCH XUẤT ---")
for i, sent in enumerate(summary_sents, 1):
    print(f"{i}. {sent}")

Ngôn ngữ tự động nhận diện: VI
Chỉ số Nội tại (Intrinsic): Silhouette Score = 0.2194 | Diversity Score = 0.8703

--- KẾT QUẢ TÓM TẮT TRÍCH XUẤT ---
1. Năm nay, thí sinh được đăng kí tối đa 15 nguyện vọng và sắp xếp theo thứ tự ưu tiên từ cao xuống thấp; đối với các thí sinh đăng kí xét tuyển vào các ngành đào tạo giáo viên, các cơ sở đào tạo chỉ xét tuyển các nguyện vọng từ 1 đến 5.
2. Đây là bước bắt buộc để hoàn tất quá trình trúng tuyển.

In [ ]:
sample_2 = """
Thị trường Tiền tệ

Thị trường ngoại tệ

Trong tuần từ 9-13/9, tỷ giá trung tâm được NHNN điều chỉnh tăng ở 3 phiên đầu tuần và giảm trở lại ở 2 phiên cuối tuần. Chốt ngày 13/9, tỷ giá trung tâm được niêm yết ở mức 24.172 VND/USD, giảm 30 đồng so với phiên cuối tuần trước đó. Sở giao dịch NHNN tiếp tục niêm yết giá mua USD ở mức 23.400 VND/USD ở tất cả các phiên trong khi niêm yết giá bán USD chốt ngày 13/9 ở mức 25.330 VND/USD, thấp hơn 50 đồng so với trần tỷ giá. Tỷ giá liên ngân hàng trong tuần từ 9-13/9 tiếp tục biến động giảm mạnh. Kết thúc phiên 13/09, tỷ giá liên ngân hàng đóng cửa tại 24.543, giảm 47 đồng so với phiên cuối tuần trước đó.

Đồng USD đã sụt giảm trở lại sau khi có thêm dữ liệu về giá sản xuất và báo cáo trợ cấp thất nghiệp, trong khi đồng EUUR tăng giá khi Ngân hàng Trung ương châu Âu (ECB) nới lỏng 25 điểm.  Chỉ số USD Index (DXY) hiện giảm 0,45%, xuống mốc 101,23. So với phiên trước đó, tỷ giá EUR so với USD tăng 0,01%, đạt 1,1078. Tỷ giá đồng bảng Anh so với USD tăng 0,06% lên 1,3131. Tỷ giá USD so Yen Nhật giảm 0,2% ở mức 141,53.

Thị trường nội tệ

Tuần từ 09/09 - 13/09, lãi suất VND LNH giảm mạnh ở tất cả các kỳ hạn từ 1M trở xuống. Chốt ngày 13/09, lãi suất VND LNH giao dịch quanh mức: ON 3,4% (-1,15 đpt); 1W 3,76% (-0,85 đpt); 2W 3,97% (-0,73 đpt); 1M 4,39% (-0,32 đpt).

Lãi suất USD LNH trong tuần qua biến động nhẹ ở tất cả các kỳ hạn. Phiên 13/09, lãi suất USD LNH đóng cửa ở mức: ON 5,31% (không đổi); 1W 5,34% (-0,01 đpt); 2W 5,34% (-0,01 đpt) và 1M 5,40% (-0,02 đpt).

Trên thị trường mở tuần qua từ 09/09 - 13/09, ở kênh cầm cố, NHNN chào thầu kỳ hạn 7 ngày với khối lượng là 18.000 tỷ đồng, lãi suất giữ ở mức 4,25%. Có 8.833,45 tỷ đồng trúng thầu, có 46.403,83 tỷ đáo hạn trong tuần qua.

NHNN không chào thầu tín phiếu NHNN và cũng không có khối lượng đáo hạn trên kênh này.

Như vậy, NHNN hút ròng 37.570,38 tỷ đồng ra thị trường trong tuần qua bằng kênh thị trường mở. Khối lượng lưu hành trên kênh cầm cố ở mức 8.833,45 tỷ đồng, không còn khối lượng tín phiếu lưu hành.

Ngày 11/09, KBNN đấu thầu thành công 13.130 tỷ đồng/14.150 tỷ đồng TPCP gọi thầu, tỷ lệ trúng thầu đạt 93%. Trong đó, kỳ hạn 7Y huy động được 165 tỷ đồng/500 tỷ đồng gọi thầu, 10Y huy động được toàn bộ 9.000 tỷ đồng gọi thầu, 15Y huy động được 3.350 tỷ đồng/3.500 tỷ đồng và 30Y huy động được 615 tỷ đồng/650 tỷ đồng gọi thầu. Kỳ hạn 5Y gọi thầu 500 tỷ đồng nhưng không có khối lượng trúng thầu. Lãi suất trúng thầu kỳ hạn 7Y là 2,05% (+0,03 đpt so với phiên đấu thầu trước), 10Y là 2,71%, 15Y 2,90% và 30Y 3,10%, đều không đổi.

Trong tuần này, ngày 18/09, KBNN dự kiến chào thầu 11.500 tỷ đồng TPCP, trong đó kỳ hạn 5Y chào thầu 500 tỷ đồng, 7Y chào thầu 500 tỷ đồng, 10Y 6.500 tỷ đồng, 15Y 3.500 tỷ đồng và 30Y chào thầu 500 tỷ đồng.

Giá trị giao dịch Outright và Repos trên thị trường thứ cấp tuần qua đạt trung bình 10335 tỷ đồng/phiên, giảm so với mức 11979 tỷ đồng/phiên của tuần trước đó. Lợi suất TPCP trong tuần qua ít biến động. Chốt phiên 13/09, lợi suất TPCP giao dịch quanh 1Y 1,86% (không đổi so với phiên cuối tuần trước); 2Y 1,88% (không đổi); 3Y 1,90% (không đổi); 5Y 1,96% (không đổi); 7Y 2,23% (-0,017 đpt); 10Y 2,72% (-0.02 đpt); 15Y 2,90% (-0,014 đpt); 30Y 3,18% (không đổi).

Thị trường Vàng

Tuần qua, giá vàng thế giới biến động mạnh vào các phiên cuối tuần nhờ triển vọng hạ lãi suất của Fed, trong khi giá vàng miếng trong nước không ghi nhận nhiều thay đổi. Hiện tại, giá vàng miếng SJC tại các cửa hàng được mua vào ở 78,50 triệu đồng/lượng và bán ra ở 80,50 triệu đồng/lượng. Vàng nhẫn trơn, ngược lại, ghi nhận biến động trong khoảng 50.000 - 500.000 đồng/lượng. Mức giá mua vào cao nhất của vàng nhẫn là 77,95 triệu đồng/lượng, trong khi giá bán ra cao nhất là 79,20 triệu đồng/lượng.

Thị trường Chứng khoán

Thế giới

Chứng khoán Mỹ tăng điểm vào ngày thứ Sáu (13/09), với S&P 500 và Nasdaq Composite ghi nhận tuần tăng mạnh nhất kể từ đầu năm 2024 đến nay trước khi diễn ra cuộc họp sắp tới của Cục Dự trữ Liên bang Mỹ (Fed).

Kết thúc phiên giao dịch ngày 13/09, chỉ số S&P 500 tiến 0.54% lên 5,626.02 điểm, thấp hơn 1% so với mức cao mọi thời đại đã đạt được vào tháng 7. Chỉ số Nasdaq Composite cộng 0.65% lên 17,683.98 điểm. Cả 2 chỉ số này đều ghi nhận 5 phiên leo dốc liên tiếp. Chỉ số Dow Jones tăng 297.01 điểm (tương đương 0.72%) lên 41,393.78 điểm.

Tiện ích, dịch vụ truyền thông và công nghiệp là những lĩnh vực dẫn đầu đà tăng của thị trường vào ngày thứ Sáu, với mỗi lĩnh vực tăng khoảng 1%.

Nhà đầu tư cũng tiếp tục mua vào các cổ phiếu chất bán dẫn và công nghệ vốn hoá lớn, qua đó giúp thúc đẩy đà phục hồi trong tuần này sau khi các cổ phiếu công nghệ bị bán tháo gần đây. Cổ phiếu Super Micro Computer và Arm Holdings lần lượt tăng 3.4% và 5.9%. Cổ phiếu Alphabet tiến 1.8% và cổ phiếu Uber vọt hon 6%.

Tuần này, S&P 500 tăng 4% và Nasdaq Composite vọt 5.9%, đánh dấu tuần tốt nhất trong năm nay của cả 2 chỉ số. Dow Jones cộng 2.6% trong tuần.

Phố Wall hiện đang hướng tới cuộc họp chính sách của Fed vào ngày 17-18/09, tại đây ngân hàng trung ương hầu hết được kỳ vọng sẽ hạ lãi suất 0.25%. Hiện tại, mức lãi suất mục tiêu của Fed là 5.25% - 5.5%.

Dữ liệu kinh tế phản ánh sự điều tiết lạm phát cũng có vẻ ủng hộ cho kỳ vọng hạ lãi suất. Chỉ số giá tiêu dùng CPI tháng 8 tại Mỹ tăng 2.5% so với cùng kỳ năm trước, mức thấp nhất kể từ tháng 2/2021. Trong khi, giá bán buôn tăng 0.2% trong tháng 8, phù hợp với dự báo.

Trong nước

Các chỉ số chính tăng giảm trái chiều trong phiên cuối tuần. Kết phiên ngày 13/09, VN-Index giảm 0.37%, về mức 1,251.71 điểm; HNX-Index tăng 0.22%, đạt 232.42 điểm. Xét cho cả tuần, VN-Index giảm tổng cộng 22.25 điểm (-1.75%), HNX-Index giảm 2.23 điểm (-0.95%).

Thị trường tiếp tục trải qua tuần giao dịch đầy khó khăn khi giảm đến 4/5 phiên trong bối cảnh thanh khoản mất hút. Việc thiếu vắng thông tin hỗ trợ và dòng tiền lớn dẫn dắt khiến tâm lý nhà đầu tư tỏ ra rất thận trọng, khối lượng giao dịch liên tiếp sụt giảm, thậm chí về mức thấp nhất kể từ đầu năm. Kết thúc phiên 13/09, VN-Index đóng cửa với mức giảm 4.64 điểm, tương đương 0.37% so với phiên trước.

Xét về mức độ đóng góp, GAS và VNM là 2 trụ cột gây áp lực lớn nhất cho chỉ số hôm nay, mỗi cổ phiếu lấy đi của VN-Index gần 1 điểm. Trong khi đó, VCB, FPT và SAB nỗ lực níu giữ mốc 1,250 điểm cho VN-Index, đóng góp hơn 1 điểm tăng.

Các nhóm ngành ghi nhận diễn biến phân hóa với mức độ biến động không quá lớn, đều dưới 1%. Ở phía tăng điểm, nhóm công nghệ thông tin dẫn đầu thị trường với mức tăng 0.52%, đóng góp chính từ FPT (+0.53%), CMG (+0.59%) và VBH (+8%). Theo sau là nhóm bất động sản và nguyên vật liệu với mức tăng khiêm tốn lần lượt là 0.23% và 0.13%.

Ở nhóm tài chính, nhiều cổ phiếu ghi nhận mức tăng nổi bật trong hôm nay như FTS (+2.33%), MBS (+1.87%), BVS (+1.79%), SSB (+1.33%), PVI (+1.57%),… Tuy nhiên, không ít cổ phiếu lớn vẫn bị sắc đỏ chi phối, mặc dù mức độ giảm không đáng kể nhưng vẫn kìm hãm sắc xanh của chỉ số ngành, tiêu biểu là BID (-0.31%), CTG (-0.29%), TCB (-0.45%), VPB (-0.27%), MBB (-0.42%) và LPB (-0.81%).

Về phía giảm điểm, nhóm tiện ích phải “đội sổ” với mức giảm 0.9%, chịu áp lực chủ yếu từ cổ phiếu vốn hóa lớn nhất ngành là GAS giảm 2.37%. Phần lớn các cổ phiếu còn lại chỉ biến động nhẹ quanh mức tham chiếu. Nhóm năng lượng cũng trải qua phiên giao dịch không mấy dễ dàng, hầu hết cổ phiếu đều bị sắc đỏ chi phối, như BSR (-0.43%), PVS (-0.74%) và PVD (-1.52%).

Nhà đầu tư nước ngoài tiếp tục bán ròng hơn 1,238 tỷ đồng trên cả hai sàn trong tuần này. Trong đó, khối ngoại bán ròng gần 1,221 tỷ đồng trên sàn HOSE và bán ròng hơn 17 tỷ đồng trên sàn HNX.
"""

lang = resolve_language(sample_2, user_choice='auto')
summary_text, summary_sents, sil_score, div_score = run_sbert_pipeline(sample_2, lang=lang, use_finetuned=True)

print(f"Ngôn ngữ tự động nhận diện: {lang.upper()}")
print(f"Chỉ số Nội tại (Intrinsic): Silhouette Score = {sil_score:.4f} | Diversity Score = {div_score:.4f}")
print(f"\n--- KẾT QUẢ TÓM TẮT TRÍCH XUẤT ---")
for i, sent in enumerate(summary_sents, 1):
    print(f"{i}. {sent}")

Ngôn ngữ tự động nhận diện: VI
Chỉ số Nội tại (Intrinsic): Silhouette Score = 0.1349 | Diversity Score = 0.6544

--- KẾT QUẢ TÓM TẮT TRÍCH XUẤT ---
1. Thị trường Tiền tệ
2. Thị trường ngoại tệ
3. Chỉ số USD Index (DXY) hiện giảm 0,45%, xuống mốc 101,23.
4. Thị trường nội tệ
5. Trên thị trường mở tuần qua từ 09/09 - 13/09, ở kênh cầm cố, NHNN chào thầu kỳ hạn 7 ngày với khối lượng là 18.000 tỷ đồng, lãi suất giữ ở mức 4,25%.
6. Thị trường Chứng khoán
7. Chỉ số Dow Jones tăng 297.01 điểm (tương đương 0.72%) lên 41,393.78 điểm.